<?php

namespace AppBundle\Repository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRepository extends \Doctrine\ORM\EntityRepository {

    public function getBrandLigier($name) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT brand
                        FROM AppBundle:Brand brand
                        WHERE brand.name = :name'
                )->setParameter('name', $name);

        $results = $query->getResult();

        // On retourne ces résultats
        return $results;
    }
    
}
