<?php

namespace AppBundle\Repository;

/**
 * FinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinitionRepository extends \Doctrine\ORM\EntityRepository
{
}
