<?php

namespace AppBundle\Repository;

/**
 * UserAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAdminRepository extends \Doctrine\ORM\EntityRepository {

    public function isUserAdmin(UserAdmin $user) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT user
                        FROM AppBundle:UserAdmin user
                        WHERE user.mail = :mail
                        AND user.password = :password'
                )->setParameter('password', $user->getMail())
                ->setParameter('mail', $user->getPassword());

        $results = $query->getSingleResult();

        return $results;
    }

    public function isOneAdmin() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT count(user.id)
                        FROM AppBundle:UserAdmin user');

        $results = $query->getSingleScalarResult();

        return $results;
    }

}
