<?php

namespace AppBundle\Repository;

/**
 * VspRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VspRepository extends \Doctrine\ORM\EntityRepository {

    public function getNumberOfVsp($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT count(vsp.id)
                        FROM AppBundle:Vsp vsp
                        WHERE vsp.type = :id'
                )->setParameter('id', $id);

        $results = $query->getSingleScalarResult();

        // On retourne ces résultats
        return $results;
    }
    
    public function getListOfNewVsp($brand) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT vsp
                        FROM AppBundle:Vsp vsp
                        INNER JOIN AppBundle:Brand brand
                        WITH vsp.brand = brand.id
                        WHERE vsp.type = :type
                        AND brand.name = :brand
                        ORDER BY vsp.price ASC'
                )->setParameter('type', 1)
                ->setParameter('brand', $brand);

        $results = $query->getResult();

        // On retourne ces résultats
        return $results;
    }
    
    public function getListOfLastVsp() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT vsp
                        FROM AppBundle:Vsp vsp
                        ORDER BY vsp.createdDate DESC'
                )->setMaxResults(4);

        $results = $query->getResult();

        // On retourne ces résultats
        return $results;
    }

}
