<?php

namespace AppBundle\Repository;

/**
 * VspTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VspTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
